---
apiVersion: v1
kind: Pod
metadata:
  name: hackme-app
  labels:
    app: hackme-app
spec:
  containers:
    - name: app
      image: tomasz2101/hackme-app:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 80
          protocol: TCP
      # Make file system read only! 
      securityContext: 
        readOnlyRootFilesystem: true
      # Fix nginx filesystem error
      volumeMounts:
        - mountPath: /var/run
          name: tmpfs-1
        - mountPath: /var/cache/nginx
          name: tmpfs-2
  volumes:
    - name: tmpfs-1
      emptyDir: {}
    - name: tmpfs-2
      emptyDir: {}
