---
apiVersion: v1
kind: Pod
metadata:
  name: hackme-app
spec:
  # Run processes as nobody and nogroup
  securityContext:
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
  containers:
    - name: app
      image: tomasz2101/hackme-app:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 80
          protocol: TCP
      # Fix nginx permissions!
      volumeMounts:
        - mountPath: /var/run
          name: tmpfs-1
        - mountPath: /var/cache/nginx
          name: tmpfs-2
  volumes:
    - name: tmpfs-1
      emptyDir: {}
    - name: tmpfs-2
      emptyDir: {}
