---
apiVersion: v1
kind: Pod
metadata:
  name: hackme-app
  labels:
    app: hackme-app
spec:
  containers:
    - name: app
      image: tomasz2101/hackme-app:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 80
          protocol: TCP
      # Disable privilege access
      securityContext:
        privileged: false
