---
apiVersion: v1
kind: Pod
metadata:
  name: hackme-app
spec:
  containers:
    - name: app
      image: tomasz2101/hackme-app:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 80
          protocol: TCP
      # Control resources
      resources:
        requests:
          memory: "32Mi"
          cpu: "50m"
        limits:
          memory: "64Mi"
          cpu: "100m"
