---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: app
      image: tomasz2101/nginx:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 80
          protocol: TCP
