---
apiVersion: v1
kind: Pod
metadata:
  name: hackme-app
  namespace: k08
  labels:
    app: hackme-app
spec:
  containers:
    - name: app
      image: tomasz2101/hackme-app:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 80
          protocol: TCP
  serviceAccount: testing-sa
  serviceAccountName: testing-sa
