---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: k08
subjects:
- kind: ServiceAccount
  name: testing-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader
