name: 'Docker build'
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --tag tomasz2101/hackme-app:$(date +%s) --file devops/docker/Dockerfile .